name: Linux

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*
  pull_request:
    branches: [ "trunk" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*

env:
  MARGS: "-j2"
  CFLAGS: "-g"

jobs:
  build:
    strategy:
      matrix:
        include: 
          - name: Default
          # -------------------------------------------------------------------------
          - name: All-static modules
            config: --enable-mods-static=reallyall
          # -------------------------------------------------------------------------
          - name: Prefork MPM, all-modules (except cgid)
            config: --enable-mods-shared=reallyall --with-mpm=prefork --disable-cgid
          # -------------------------------------------------------------------------
          - name: Worker MPM, all-modules
            config: --enable-mods-shared=reallyall --with-mpm=worker
          # -------------------------------------------------------------------------
          - name: Shared MPMs, all-modules
            config: --enable-mods-shared=reallyall --enable-mpms-shared=all
          # -------------------------------------------------------------------------
          - name: Event MPM, all-modules, mod_cgid only
            config: --enable-mods-shared=reallyall --with-mpm=event --disable-cgi
          # -------------------------------------------------------------------------
          - name: Event MPM, all-modules, no CMSG_DATA
            config: --enable-mods-shared=reallyall --with-mpm=event ac_cv_have_decl_CMSG_DATA=no
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      NOTEST_CFLAGS: ${{ matrix.notest-cflags }}
      CONFIG: ${{ matrix.config }}
    name: ${{ matrix.name }}
    steps:
    - name: apt refresh
      run: sudo apt-get -o Acquire::Retries=5 update
    - name: Install prerequisites
      run: sudo apt-get install -o Acquire::Retries=5
                    cpanminus libtool-bin libapr1-dev libaprutil1-dev
                    liblua5.3-dev libbrotli-dev libcurl4-openssl-dev     
                    libnghttp2-dev libjansson-dev libpcre2-dev gdb
                    perl-doc
    - uses: actions/checkout@v3
    - name: Configure environment
      run: ./test/travis_before_linux.sh
    - name: Build and test
      run: ./test/travis_run_linux.sh
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: error_log
        path: test/perl-framework/t/logs/error_log

